### ISSUE TITLE
News / Blog Site

### ISSUE THREAD

**Issue by davethegr8** [cascadiajs/2016.cascadiajs.com#7]
Going forward for CascadiaFEST, we're going to build out what boils down to a blog to make news posts. We'll be able to re-use this every year rather than rebuilding it year after year for whatever our current site build system is.

For now, these are the specs/requirements:
- Use Jekyll
- Tag/Categorize posts with years (2015, 2016, etc)
- Specify a layout/stylesheet/theme for each post (to match each year's design)
- Author posts with Markdown or HTML
- Request a list of posts by tag/category (example: 2016) ordered by date. HTML & JSON response.
- Host with Surge.sh
- Build/deploy with Travis on commit to master

**Comment by kennethormandy** [comment]
If you want a basis / something to evaluate, I open sourced [Lost Type’s blog](http://blog.losttype.com) at [losttype/blog.losttype.com](https://github.com/losttype/blog.losttype.com). It’s definitely not “finished” and I would have some reservations about using Metalsmith again (I found it challenging to get a development environment that ran quickly enough to work properly in a lot of situations), but it does meet most of your requirements:
- Uses Metalsmith (Sass, Handelbars)
- Custom categories with custom layouts (ex. [Field Trip Chicago](http://blog.losttype.com/fieldtripchi/), [Field Trip New York](http://blog.losttype.com/fieldtripny))
- Multiple authors
- Setup to work with [Prose.io](https://prose.io)
- Built-in deployment to Surge via Travis
- Also deploys Pull Requests to a different subdomain, for previewing draft blog posts (ex. pr-13.blog.cascadiafest.surge.sh)

It’s not open license because we didn’t want to have someone copy the design outright, but if there’s anything you find you want to use, that can probably be revised. At least might be helpful when evaluating.

Personally, the main thing I would do differently would be to find a Metalsmith config that can continue to run quickly with a lot of posts or possibly even use something different, (Jekyll solved this by letting you only use one post at a time, Harp dynamically compiles based on requests rather than building the entire site, I didn’t find a good equivalent solution for Metalsmith). This can also make it quite slow when you are deploying via Travis. That said, it is awesome how much you can get out of it as a static site generator when you need advanced blog features, and I am happy with the result you get.

Hopefully that’s helpful!

**Comment by KatieK2** [comment]
Idea for news post: 

What is a CascadiaFest?

CascadiaCSS + CascadiaJS
3 days, volunteer run, for developers, by developers, PacNW focused
Favorite moments from past years
benefits of Semiahmoo

Probably ask Ruth to do copy-writing / make-it-good-ification.

**Comment by davethegr8** [comment]
Thanks for the input @kennethormandy, it's helpful to hear others' experiences. I think my biggest concern with MetalSmith is that it's got a lack of good documentation, so when I run into problems it's hard to work my way through them.

I didn't know about Jekyll's new incremental compilation, so that might change my thinking. My issue with Harp specifically right now is that there are different outputs for `compile` vs `serve`, it's not hard to work around when it happens but I'd rather not have to worry about it.

Did you use `metalsmith-serve` by any chance? It's similar to jekyll's `--incremental`

**Comment by kennethormandy** [comment]
I’m not sure I follow about things being different between `harp server` and `compile`, but just to clarify, I wasn’t trying to advocate for it. I think Metalsmith is a sensible choice in this case.

I was using metalsmith-serve, but with a `metalsmith.json` rather than `.js` file, so maybe I didn’t realise that was possible. Do you hard-code what files you want served?

**Comment by davethegr8** [comment]
No... it just makes your build folder accessible. Maybe I'm thinking of the watch plugin, which seems to do incremental compilation as well.

**Comment by KatieK2** [comment]
Moar article ideas:
- How to convince your boss to send you to CascadiaFest. 
- How to convince your company to sponsor CascadiaFest.

Related: http://blog.movingworlds.org/how-to-ask-for-a-sabbatical-in-2016-even-if-your-company-doesnt-have-a-program/

**Comment by davethegr8** [comment]
@kennethormandy I took your pr deploy to different domain idea and a couple other bits of inspiration from your travis config. Thanks!

Now we just need to incorporate the json feed into the 2016 cascadia website
