### ISSUE TITLE
Website update stuffs

### ISSUE THREAD

**Issue by KatieK2** [cascadiajs/2016.cascadiajs.com#9]
Just a few things I noticed:
- Myles' is missing
- Remove the "CFP is open" copy. Perhaps Ruth could advise on the next messaging we'd like to promote.
- Can we add the CascadiaCSS Twitter account? https://twitter.com/cascadiacss

**Comment by RuthieB** [comment]
Something simple like: 

Our call for proposals is now closed, thanks to all who submitted! Stay tuned for speaker announcements in May. 

And maybe also:

Follow our twitter accounts <links here> to get updates on the schedule and ticket sales.

**Comment by davethegr8** [comment]
@KatieK2 
- myles has asked to not be published at this point.
- I'm trying to get the website into a shippable point before doing many copy changes, but yes we will be changing this
- Yeah, we'll get that included

**Comment by alexlande** [comment]
Suggestion: right now, on wide screens, the top of the mountain background is cut off due because the `background-position` is set to `bottom center`. If it was changed to `top center`, the mountain would never be cut off.

### Before

<img width="1280" alt="before" src="https://cloud.githubusercontent.com/assets/808159/14753523/c4a4ee3c-088a-11e6-925a-79ee953ab696.png">

### After

<img width="1280" alt="after" src="https://cloud.githubusercontent.com/assets/808159/14753528/c835b4b4-088a-11e6-8c58-b5cd2775c01b.png">
